"""Correctness reviewer using a powerful model to check explanations.

Uses Opus to verify factual claims in explanations generated by cheaper models.
Instead of abstract scoring dimensions, asks specific questions about correctness.
"""

import json
from typing import Any

from anthropic import AsyncAnthropic

REVIEW_SYSTEM_PROMPT = """\
You are an expert reviewer of assembly language explanations. Your job is to \
verify the factual correctness of explanations generated by another AI model.

You will receive:
1. Source code and compilation options
2. The assembly output
3. An explanation of that assembly

Your task is to check the explanation for factual errors. Focus on:
- **Instruction semantics**: Are instructions correctly described? (e.g., does \
`lea` actually access memory, or just compute an address?)
- **Register usage**: Are calling conventions and register purposes correct?
- **Optimisation claims**: Are claims about what optimisations were applied accurate?
- **Complexity/performance claims**: Are any Big-O or performance claims correct?
- **Optimisation level characterisation**: If the code is unoptimised (no flags), \
does the explanation say so confidently rather than hedging?
- **Completeness**: Are important aspects of the assembly missed entirely?

Respond with a JSON object (no markdown fencing):
{
  "correct": true/false,
  "issues": [
    {
      "severity": "error" | "warning",
      "claim": "The specific claim from the explanation",
      "correction": "What's actually correct",
      "location": "Brief quote from the explanation where this appears"
    }
  ],
  "summary": "One-line overall assessment"
}

"error" = factually wrong (would mislead a student)
"warning" = imprecise, misleading, or could be better but not strictly wrong

If the explanation is fully correct, return {"correct": true, "issues": [], \
"summary": "..."}."""

REVIEW_USER_TEMPLATE = """\
## Source code ({language}, compiled with {compiler} {options})
```
{code}
```

## Assembly ({arch})
```
{assembly}
```

## Explanation to review
{explanation}"""


class CorrectnessReviewer:
    """Reviews explanations for factual correctness using a powerful model."""

    def __init__(self, model: str = "claude-opus-4-7"):
        self.model = model
        self.client = AsyncAnthropic()

    async def review(
        self,
        *,
        language: str,
        compiler: str,
        options: list[str],
        arch: str,
        code: str,
        assembly: str,
        explanation: str,
    ) -> dict[str, Any]:
        """Review a single explanation for correctness.

        Returns a dict with 'correct' (bool), 'issues' (list), 'summary' (str).
        """
        user_prompt = REVIEW_USER_TEMPLATE.format(
            language=language,
            compiler=compiler,
            options=" ".join(options) if options else "(no flags)",
            code=code,
            arch=arch or "unknown",
            assembly=assembly,
            explanation=explanation,
        )

        # Opus 4.7+ rejects `temperature`; rely on the model's own default.
        msg = await self.client.messages.create(
            model=self.model,
            max_tokens=2048,
            system=REVIEW_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )

        text = msg.content[0].text.strip()

        # Parse JSON response
        try:
            result = json.loads(text)
        except json.JSONDecodeError:
            # Try to extract JSON from markdown fencing
            if "```" in text:
                json_part = text.split("```")[1]
                if json_part.startswith("json"):
                    json_part = json_part[4:]
                result = json.loads(json_part.strip())
            else:
                result = {
                    "correct": None,
                    "issues": [],
                    "summary": f"Failed to parse reviewer response: {text[:200]}",
                }

        result["reviewer_model"] = self.model
        result["reviewer_input_tokens"] = msg.usage.input_tokens
        result["reviewer_output_tokens"] = msg.usage.output_tokens

        return result

    async def review_test_result(
        self,
        test_case: dict[str, Any],
        explanation: str,
    ) -> dict[str, Any]:
        """Review a test result using the test case data."""
        inp = test_case["input"]
        asm_text = "\n".join(a["text"] for a in inp["asm"] if isinstance(a, dict) and "text" in a)

        return await self.review(
            language=inp.get("language", "unknown"),
            compiler=inp.get("compiler", "unknown"),
            options=inp.get("compilationOptions", []),
            arch=inp.get("instructionSet", "unknown"),
            code=inp.get("code", ""),
            assembly=asm_text,
            explanation=explanation,
        )
