[project]
name = "explain"
version = "0.1.0"
description = "Explain Compiler Explorer output using AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.51.0",
    "aws-embedded-metrics>=3.3.0",
    "fastapi",
    "mangum",
    "pydantic-settings>=2.9.1",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    # In development mode, include the FastAPI development server.
    "fastapi[standard]>=0.115",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]
