name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for OIDC login

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Run pre-commit
        run: uv run pre-commit run --all

      - name: Run tests
        run: uv run pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::052730242331:role/github-actions/explain-ci
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build docker image
        run: docker build -t compiler-explorer/explain .

      - name: Push docker image to Amazon ECR Public
        if: github.ref == 'refs/heads/main'
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: l7x5u0s5
          REPOSITORY: compiler-explorer/explain
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag compiler-explorer/explain $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
